---
abstract: unknown
author:
  - 'Rene Schickbauer <rene.schickbauer@magnapowertrain.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Server-Mail-ESMTP-SIZE
no_index:
  directory:
    - t
    - inc
requires:
  Net::Server::Mail::ESMTP: 0
  Test::SMTP: 0.02
  Test::Simple: 0.44
version: 0.03
